name: publish-to-npm
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  publish-to-npm:
    name: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm i
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}